//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.AspNetCore.SDK.LayoutService.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sitecore.AspNetCore.SDK.LayoutService.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract registrations must provide a factory to resolve a layout service..
        /// </summary>
        internal static string Exception_AbstractRegistrationsMustProvideFactory {
            get {
                return ResourceManager.GetString("Exception_AbstractRegistrationsMustProvideFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not contact the Sitecore layout service..
        /// </summary>
        internal static string Exception_CouldNotContactService {
            get {
                return ResourceManager.GetString("Exception_CouldNotContactService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert field of type {0} into type {1}.
        /// </summary>
        internal static string Exception_CouldNotConvertFieldToType {
            get {
                return ResourceManager.GetString("Exception_CouldNotConvertFieldToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find converter for {0}..
        /// </summary>
        internal static string Exception_CouldNotFindConverter {
            get {
                return ResourceManager.GetString("Exception_CouldNotFindConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an array or object when deserializing a {0}.  Found {1}..
        /// </summary>
        internal static string Exception_DeserializationOfIncorrectToken {
            get {
                return ResourceManager.GetString("Exception_DeserializationOfIncorrectToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with the Sitecore layout service..
        /// </summary>
        internal static string Exception_GeneralServiceError {
            get {
                return ResourceManager.GetString("Exception_GeneralServiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler name cannot be null..
        /// </summary>
        internal static string Exception_HandlerNameIsNull {
            get {
                return ResourceManager.GetString("Exception_HandlerNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} key cannot be found in the handler registry..
        /// </summary>
        internal static string Exception_HandlerRegistryKeyNotFound {
            get {
                return ResourceManager.GetString("Exception_HandlerRegistryKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid request was sent to the Sitecore layout service..
        /// </summary>
        internal static string Exception_InvalidRequestError {
            get {
                return ResourceManager.GetString("Exception_InvalidRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sitecore layout service returned a response in an invalid format..
        /// </summary>
        internal static string Exception_InvalidResponseFormat {
            get {
                return ResourceManager.GetString("Exception_InvalidResponseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sitecore layout service returned an item not found response..
        /// </summary>
        internal static string Exception_ItemNotFoundError {
            get {
                return ResourceManager.GetString("Exception_ItemNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sitecore layout service returned a server error..
        /// </summary>
        internal static string Exception_LayoutServiceServerError {
            get {
                return ResourceManager.GetString("Exception_LayoutServiceServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while configuring the HTTP message..
        /// </summary>
        internal static string Exception_MessageConfigurationError {
            get {
                return ResourceManager.GetString("Exception_MessageConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Field could not be read as the type {0}.
        /// </summary>
        internal static string Exception_ReadingField {
            get {
                return ResourceManager.GetString("Exception_ReadingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only register implementations of {0} as layout services..
        /// </summary>
        internal static string Exception_RegisterTypesOfService {
            get {
                return ResourceManager.GetString("Exception_RegisterTypesOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Status Code.
        /// </summary>
        internal static string HttpStatusCode_KeyName {
            get {
                return ResourceManager.GetString("HttpStatusCode_KeyName", resourceCulture);
            }
        }
    }
}
