//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.AspNetCore.SDK.RenderingEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sitecore.AspNetCore.SDK.RenderingEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to dynamically create an instance of &apos;{0}&apos;.
        /// </summary>
        internal static string Exception_CannotCreateModelInstance {
            get {
                return ResourceManager.GetString("Exception_CannotCreateModelInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find appropriate &apos;BindView&apos; method to execute for the model..
        /// </summary>
        internal static string Exception_CannotFindBindViewMethodOnViewComponent {
            get {
                return ResourceManager.GetString("Exception_CannotFindBindViewMethodOnViewComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a valid renderer for the type {0}..
        /// </summary>
        internal static string Exception_CannotFindValidRenderer {
            get {
                return ResourceManager.GetString("Exception_CannotFindValidRenderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component with id &apos;{0}&apos; name cannot be null or empty..
        /// </summary>
        internal static string Exception_ComponentNameNotDefined {
            get {
                return ResourceManager.GetString("Exception_ComponentNameNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The component renderer descriptor for {0} is null. Please ensure that correct Sitecore component-to-view mappings are defined as part of the AddSitecoreRenderingEngine options in Startup.ConfigureServices..
        /// </summary>
        internal static string Exception_ComponentRendererDescriptorIsNull {
            get {
                return ResourceManager.GetString("Exception_ComponentRendererDescriptorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SitecoreRenderingContext controller cannot be null..
        /// </summary>
        internal static string Exception_ControllerCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_ControllerCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve endpoint data..
        /// </summary>
        internal static string Exception_CouldNotResolveEndpointData {
            get {
                return ResourceManager.GetString("Exception_CouldNotResolveEndpointData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpRequest cannot be null..
        /// </summary>
        internal static string Exception_HttpRequestCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_HttpRequestCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RenderingEngineMiddleware can only be executed once. Make sure global rendering engine configuration is not mixed with attribute based one..
        /// </summary>
        internal static string Exception_InvalidRenderingEngineConfiguration {
            get {
                return ResourceManager.GetString("Exception_InvalidRenderingEngineConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelType parameter cannot be null..
        /// </summary>
        internal static string Exception_ModelTypeCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_ModelTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering Context cannot be null..
        /// </summary>
        internal static string Exception_RenderingContextCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_RenderingContextCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering Context Component cannot be null..
        /// </summary>
        internal static string Exception_RenderingContextComponentCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_RenderingContextComponentCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-nullable value must be provided for the RequestMappings action list..
        /// </summary>
        internal static string Exception_RequestMappings_Required {
            get {
                return ResourceManager.GetString("Exception_RequestMappings_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected to find &apos;{0}&apos; method on type &apos;{1}&apos;..
        /// </summary>
        internal static string Exception_RouteDoesNotHaveAsRouteMethod {
            get {
                return ResourceManager.GetString("Exception_RouteDoesNotHaveAsRouteMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find field &apos;{0}&apos; on Component &apos;{1}&apos;..
        /// </summary>
        internal static string Exception_ScTextComponentFieldNameCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_ScTextComponentFieldNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;sc-text&apos; {0} property cannot be null..
        /// </summary>
        internal static string Exception_ScTextComponentNull {
            get {
                return ResourceManager.GetString("Exception_ScTextComponentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SitecoreLayout cannot be null..
        /// </summary>
        internal static string Exception_SitecoreLayoutCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_SitecoreLayoutCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sitecore Rendering Engine Middleware cannot be enabled without the Rendering Engine Services being registered first. Did you forget to invoke the AddSitecoreRenderingEngine() extension method in Startup.ConfigureServices?.
        /// </summary>
        internal static string Exception_SitecoreRenderingEngineServicesNotRegistered {
            get {
                return ResourceManager.GetString("Exception_SitecoreRenderingEngineServicesNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must implement &apos;{1}&apos;.
        /// </summary>
        internal static string Exception_TypeMustImplementInterface {
            get {
                return ResourceManager.GetString("Exception_TypeMustImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected model type: {0}..
        /// </summary>
        internal static string Exception_UnexpectedModelType {
            get {
                return ResourceManager.GetString("Exception_UnexpectedModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewContext parameter cannot be null..
        /// </summary>
        internal static string Exception_ViewContextCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_ViewContextCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder name was not defined..
        /// </summary>
        internal static string Warning_PlaceholderNameWasNotDefined {
            get {
                return ResourceManager.GetString("Warning_PlaceholderNameWasNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder &apos;{0}&apos; was empty..
        /// </summary>
        internal static string Warning_PlaceholderWasEmpty {
            get {
                return ResourceManager.GetString("Warning_PlaceholderWasEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder was not defined..
        /// </summary>
        internal static string Warning_PlaceholderWasNotDefined {
            get {
                return ResourceManager.GetString("Warning_PlaceholderWasNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Render method called. Component name: {1}.
        /// </summary>
        internal static string Warning_RenderMethodCalled {
            get {
                return ResourceManager.GetString("Warning_RenderMethodCalled", resourceCulture);
            }
        }
    }
}
