//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.AspNetCore.SDK.Pages.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sitecore.AspNetCore.SDK.Pages.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Service GraphQL Response : {responseDataLayout}.
        /// </summary>
        internal static string Debug_LayoutServiceGraphQLResponse {
            get {
                return ResourceManager.GetString("Debug_LayoutServiceGraphQLResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout Service Response JSON.
        /// </summary>
        internal static string Debug_LayoutServiceResponseJSON {
            get {
                return ResourceManager.GetString("Debug_LayoutServiceResponseJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing valid Pages Config request.
        /// </summary>
        internal static string Debug_ProcessingValidPagesConfigRequest {
            get {
                return ResourceManager.GetString("Debug_ProcessingValidPagesConfigRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing valid Pages Render request..
        /// </summary>
        internal static string Debug_ProcessingValidPagesRenderRequest {
            get {
                return ResourceManager.GetString("Debug_ProcessingValidPagesRenderRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pages Editing Origin.
        /// </summary>
        internal static string Error_InvalidPagesEditingOrigin {
            get {
                return ResourceManager.GetString("Error_InvalidPagesEditingOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pages Editing Secret Value.
        /// </summary>
        internal static string Error_InvalidPagesEditingSecretValue {
            get {
                return ResourceManager.GetString("Error_InvalidPagesEditingSecretValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditingScriptsTagHelper: Sitecore RenderingContext is Null.
        /// </summary>
        internal static string Exception_EditingScriptsTagHelperSitecoreRenderingContextNull {
            get {
                return ResourceManager.GetString("Exception_EditingScriptsTagHelperSitecoreRenderingContextNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditingScriptsTagHelper: Unable to process ContextRawData.
        /// </summary>
        internal static string Exception_EditingScriptsTagHelperUnableToProcessContextRawData {
            get {
                return ResourceManager.GetString("Exception_EditingScriptsTagHelperUnableToProcessContextRawData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphQLEditingServiceHandler: Error attempting to process non-editing request.
        /// </summary>
        internal static string Exception_ErrorAttemptingToProcessNonEditingRequest {
            get {
                return ResourceManager.GetString("Exception_ErrorAttemptingToProcessNonEditingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PagesRenderMiddleware already registered.
        /// </summary>
        internal static string Exception_PagesRenderMiddlewareAlreadyRegistered {
            get {
                return ResourceManager.GetString("Exception_PagesRenderMiddlewareAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphQLEditingServiceHandler.HandleEditingLayoutRequest: Response is null, unable to process EditingResponse.
        /// </summary>
        internal static string Exception_UableToProcessEditingResponse {
            get {
                return ResourceManager.GetString("Exception_UableToProcessEditingResponse", resourceCulture);
            }
        }
    }
}
